package review

import (
	"context"
	"fmt"
	"time"

	"github.com/chakkapong1999/ai-assistance/backend/internal/config"
)

// Mock is a Reviewer that never calls an LLM. Its scenarios let the queue,
// retry, snooze and dashboard be exercised without spending quota.
type Mock struct {
	Scenario string
	Delay    time.Duration
}

func (m Mock) Review(ctx context.Context, req Request) (Result, error) {
	if m.Delay > 0 {
		select {
		case <-time.After(m.Delay):
		case <-ctx.Done():
			return Result{}, ctx.Err()
		}
	}

	switch m.Scenario {
	case config.ScenarioClean:
		return Result{Summary: "Mock review: no issues found.", Model: ModelMock}, nil

	case config.ScenarioInvalidJSON:
		// Go through the real parser so the error is exactly what a bad model answer gives.
		_, err := ParseOutput([]byte("this is not json {"))
		return Result{}, err

	case config.ScenarioUsageLimit:
		return Result{}, &UsageLimitError{RetryAfter: 30 * time.Second, Message: "mock usage limit"}

	case config.ScenarioTimeout:
		return Result{}, ErrTimeout

	case config.ScenarioFindings, "":
		return m.findings(req), nil
	}
	return Result{}, fmt.Errorf("review: unknown mock scenario %q", m.Scenario)
}

// findings points at the first added line of the chunk so the result survives
// Sanitize, and includes one suggestion so the diff/suggestion UI has data.
func (m Mock) findings(req Request) Result {
	res := Result{Summary: "Mock review: generated findings for testing.", Model: ModelMock}
	for _, p := range req.Chunk.Parts {
		for _, h := range p.Hunks {
			for _, l := range h.Lines {
				if l.Kind != '+' {
					continue
				}
				res.Findings = []Finding{
					{
						FilePath: p.Path, LineStart: l.NewNo, LineEnd: l.NewNo,
						Severity: SeverityMajor, Category: CategoryBug,
						Title:       "Mock: possible unhandled error",
						Explanation: "This finding is generated by the mock reviewer and is not a real review.",
						Suggestion: &Suggestion{
							Original:  l.Text,
							Suggested: l.Text + " // TODO(mock): handle error",
						},
					},
					{
						FilePath: p.Path, LineStart: l.NewNo, LineEnd: l.NewNo,
						Severity: SeverityMinor, Category: CategoryStyle,
						Title:       "Mock: naming could be clearer",
						Explanation: "Second mock finding so ordering and counts can be checked.",
					},
				}
				return res
			}
		}
	}
	return res // chunk had no added lines (e.g. only removals)
}
